# Generated by Django 5.2.5 on 2025-08-23 09:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_quizhistory_delete_useranswer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizHistory',
            new_name='History',
        ),
    ]
