# Generated by Django 5.2.5 on 2025-08-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_rename_quizhistory_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
